name: flutter_build_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^3.16.8

msix_config:
  display_name: flutter_build_test
  publisher_display_name: flutter_build_test_company
  identity_name: com.example.flutter.build.test
  msix_version: 1.0.0.0
  
  # certificate:
  #   generate: false
  #   path: flutter_build_test.p12
  #   password: flutter_build_test

  certificate_path: flutter_build_test.crt
  certificate_password: flutter_build_test
  
  icons:
    background_color: white
    show_name: true
  
  capabilities: internetClient,privateNetworkClientServer
  
  start_menu:
    name: flutter_build_test
    icon: true

flutter:
  uses-material-design: true
