name: flutter_build_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^3.16.8

msix_config:
  display_name: flutter_build_test1
  publisher_display_name: flutter_build_test_company
  identity_name: com_example_flutter_build_test
  msix_version: 1_0_0_0
  
  certificate:
    generate: true
    subject: CN=flutter_build_test2
  
  icons:
    background_color: white
    show_name: true
  
  capabilities: internetClient,privateNetworkClientServer
  
  start_menu:
    name: flutter_build_test3
    icon: true

flutter:
  uses-material-design: true
