name: flutter_build_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^3.16.8

msix_config:
  display_name: "Flutter Build Test"
  publisher_display_name: "Your Company"
  identity_name: "com.example.flutterbuildtest"
  msix_version: "1.0.0.0"
  
  certificate:
    generate: true
    subject: "CN=Flutter Build Test"
  
  icons:
    background_color: "white"
    show_name: true
  
  capabilities: "internetClient,privateNetworkClientServer"
  
  start_menu:
    name: "Flutter Build Test"
    icon: true

flutter:
  uses-material-design: true
