name: Flutter PC Build and Release

on:
  push:
    branches:
      - 'release/0.0.1'
      - /^release\/.*$/

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    outputs:
      appName: ${{ steps.get_app_info.outputs.appName || steps.get_app_info_win.outputs.appName }}
      appVersion: ${{ steps.get_app_info.outputs.appVersion || steps.get_app_info_win.outputs.appVersion }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 获取应用信息
      - name: Get app version and name
        id: get_app_info
        if: matrix.os != 'windows-latest'
        run: |
          APP_VERSION=$(grep -E '^version:' pubspec.yaml | awk '{print $2}' | tr -d "'")
          APP_NAME=$(grep -E '^name:' pubspec.yaml | awk '{print $2}')
          echo "::set-output name=appVersion::$APP_VERSION"
          echo "::set-output name=appName::$APP_NAME"
          echo "appVersion=$APP_VERSION" >> $GITHUB_ENV
          echo "appName=$APP_NAME" >> $GITHUB_ENV
        shell: bash

      - name: Get app version and name (Windows)
        if: matrix.os == 'windows-latest'
        id: get_app_info_win
        run: |
          $APP_VERSION = (Get-Content -Path pubspec.yaml | Select-String -Pattern 'version:' | ForEach-Object { $_.Line.Split(':')[1].Trim() })
          $APP_NAME = (Get-Content -Path pubspec.yaml | Select-String -Pattern 'name:' | ForEach-Object { $_.Line.Split(':')[1].Trim() })
          echo "::set-output name=appVersion::$APP_VERSION"
          echo "::set-output name=appName::$APP_NAME"
          echo "appVersion=$APP_VERSION" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "appName=$APP_NAME" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh

      - name: Print APP_NAME and APP_VERSION
        run: |
          echo "The app name is ${{ env.appName }}"
          echo "The app version is ${{ env.appVersion }}"

      - name: Set up Flutter
        id: flutter-env
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Setup Flutter environment
        run: flutter pub get

      # macOS 构建
      - name: Build macOS app
        if: matrix.os == 'macos-latest'
        run: |
          flutter build macos --release
          mkdir -p release

      - name: Install create-dmg
        if: matrix.os == 'macos-latest'
        run: brew install create-dmg

      - name: Create DMG for macOS
        if: matrix.os == 'macos-latest'
        run: |
          create-dmg \
            --volname "${{ env.appName }} ${{ env.appVersion }} Installer" \
            --background "assets/images/install_background.png" \
            --window-pos 200 120 \
            --window-size 600 400 \
            --icon "${{ env.appName }}.app" 200 190 \
            --app-drop-link 400 185 \
            "release/release-${{ env.appName }}-${{ env.appVersion }}.dmg" \
            "build/macos/Build/Products/Release/${{ env.appName }}.app"

      # Windows 构建
      - name: Create MSIX package
        if: matrix.os == 'windows-latest'
        run: |
          # 设置环境变量以自动接受证书安装
          $env:MSIX_AUTO_INSTALL_CERT = "true"
          $env:MSIX_CERT_PASSWORD = "password"

          # 创建 MSIX 包
          echo y | dart run msix:create

          echo "The app name is ${{ env.appName }}"
          echo "The app version is ${{ env.appVersion }}"

          $sourceFile = "build\windows\x64\runner\Release\flutter_build_test.msix"
          $destinationFolder = "release"
          $newFileName = "release-${{ env.appName }}-${{ env.appVersion }}.msix"

          Copy-Item -Path $sourceFile -Destination $destinationFolder -NewName $newFileName

      # 上传构建产物
      - name: Upload macOS artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: macos-artifact
          path: ./release/release-${{ env.appName }}-${{ env.appVersion }}.dmg

      - name: Upload Windows artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: windows-artifact
          path: ./release/release-${{ env.appName }}-${{ env.appVersion }}.msix

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 下载构建产物
      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: macos-artifact
          path: ./release

      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-artifact
          path: ./release

      # 上传 release
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          VERSION: ${{ needs.build.outputs.appVersion }}
        with:
          tag_name: "v${{ steps.get_version_name.outputs.appVersion }}"
          name: Release ${{ needs.build.outputs.appName }} ${{ needs.build.outputs.appVersion }}
          body: 'Flutter PC Build and Release'
          draft: false
          prerelease: false
          files: |
            release/release-${{ needs.build.outputs.appName }}-${{ needs.build.outputs.appVersion }}.dmg
            release/release-${{ needs.build.outputs.appName }}-${{ needs.build.outputs.appVersion }}.msix

  merge:
    needs: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/*')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge to Main/Master
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          MAIN_BRANCH="main"
          CURRENT_BRANCH=$(echo $GITHUB_REF | cut -d'/' -f3)

          git fetch origin $MAIN_BRANCH
          git checkout $MAIN_BRANCH
          git pull origin $MAIN_BRANCH

          git merge --no-ff $CURRENT_BRANCH -m "Merge branch '$CURRENT_BRANCH' into $MAIN_BRANCH"
          git push origin $MAIN_BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
