name: Flutter Build and Release

on:
  push:
    branches:
      - 'release/0.0.1'
      - /^release\/.*$/

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # macOS/Linux get app version and name

      - name: Get app version and name for macOS/Linux
        if: matrix.os != 'windows-latest'
        run: |
          APP_VERSION=$(grep -E '^version:' pubspec.yaml | awk '{print $2}' | tr -d "'")
          APP_NAME=$(grep -E '^name:' pubspec.yaml | awk '{print $2}')
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
        shell: bash

      - name: Print APP_NAME and APP_VERSION for macOS/Linux
        if: matrix.os != 'windows-latest'
        run: |
          echo "The app name is ${{ env.APP_NAME }}"
          echo "The app version is ${{ env.APP_VERSION }}"
        shell: bash

      # Windows get app version and name

      - name: Get app version and name for Windows
        if: matrix.os == 'windows-latest'
        run: |
          $APP_NAME = (Get-Content -Path pubspec.yaml | Select-String -Pattern 'name:' | ForEach-Object { $_.Line.Split(':')[1].Trim() })
          $APP_VERSION = (Get-Content -Path pubspec.yaml | Select-String -Pattern 'version:' | ForEach-Object { $_.Line.Split(':')[1].Trim() })
          echo "APP_VERSION=$APP_VERSION" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "APP_NAME=$APP_NAME" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh

      - name: Print APP_NAME and APP_VERSION  for Windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "The app name is ${{ env.APP_NAME }}"
          echo "The app version is ${{ env.APP_VERSION }}"
        shell: pwsh

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Setup Flutter environment
        run: flutter pub get

      - name: Determine branch type
        id: determine-branch
        run: echo "::set-output name=branch_type::$(if [[ $GITHUB_REF =~ ^refs/heads/release/.*$ ]]; then echo 'release'; else echo 'other'; fi)"
        shell: bash

      # - name: Build and package app for macOS
      #   if: matrix.os == 'macos-latest' && steps.determine-branch.outputs.branch_type == 'release'
      #   run: |
      #     flutter build macos --release
      #     mkdir -p release
      #     hdiutil create -volname "${{ env.APP_NAME }}" \
      #                    -srcfolder "build/macos/Build/Products/Release/${{ env.APP_NAME }}.app" \
      #                    -ov -format UDZO "release/release-${{ env.APP_NAME }}-${{ env.APP_VERSION }}.dmg"
      #   shell: bash
      - name: Build and package app for macOS
        if: matrix.os == 'macos-latest'
        run: |
          flutter build macos --release
          mkdir -p release

      - name: Install create-dmg via Homebrew
        if: matrix.os == 'macos-latest'
        run: |
          brew install create-dmg

      - name: Create DMG using create-dmg
        if: matrix.os == 'macos-latest'
        run: |
          APP_NAME=${{ env.APP_NAME }}
          APP_VERSION=${{ env.APP_VERSION }}
          create-dmg \
            --volname "$APP_NAME $APP_VERSION Installer" \
            --background "assets/images/install_background.png" \
            --window-pos 200 120 \
            --window-size 600 400 \
            --icon "MyApp.app" 200 190 \
            --hide-extension "MyApp.app" \
            --app-drop-link 400 185 \
            "release/release-$APP_NAME-$APP_VERSION.dmg" \
            "build/macos/Build/Products/Release/$APP_NAME.app"

      - name: Build and package app for Windows
        if: matrix.os == 'windows-latest' && steps.determine-branch.outputs.branch_type == 'release'
        run: |
          flutter build windows --release
          mkdir -p release
          cp "build/windows/x64/runner/Release/${{ env.APP_NAME }}.exe" "release/release-${{ env.APP_NAME }}-${{ env.APP_VERSION }}.exe"
        shell: pwsh

      - name: Create GitHub Release
        id: create_release
        if: matrix.os == 'macos-latest'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: 'v${{ env.APP_VERSION }}'
          release_name: 'Release ${{ env.APP_NAME }} ${{ env.APP_VERSION }}'
          body: 'Release of Flutter PC build'

      - name: Debug upload URL
        run: |
          echo "Upload URL: ${{ steps.create_release.outputs.upload_url }}"

  upload_assets:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug upload URL
        run: |
          echo "needs1 : ${{ needs }}"
          echo "needs2 : ${{ needs.build }}"
          echo "needs3 : ${{ needs.build.outputs }}"
          echo "needs4 : ${{ needs.build.outputs.upload_url }}"
          echo "needs4 : ${{ needs.build.outputs.create_release }}"
          echo "needs5 : ${{ needs.build.outputs.create_release.upload_url }}"

      # macOS/Linux get app version and name

      - name: Get app version and name for macOS/Linux
        if: matrix.os != 'windows-latest'
        run: |
          APP_VERSION=$(grep -E '^version:' pubspec.yaml | awk '{print $2}' | tr -d "'")
          APP_NAME=$(grep -E '^name:' pubspec.yaml | awk '{print $2}')
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
        shell: bash

      - name: Print APP_NAME and APP_VERSION for macOS/Linux
        if: matrix.os != 'windows-latest'
        run: |
          echo "The app name is ${{ env.APP_NAME }}"
          echo "The app version is ${{ env.APP_VERSION }}"
        shell: bash

      # Windows get app version and name

      - name: Get app version and name for Windows
        if: matrix.os == 'windows-latest'
        run: |
          $APP_NAME = (Get-Content -Path pubspec.yaml | Select-String -Pattern 'name:' | ForEach-Object { $_.Line.Split(':')[1].Trim() })
          $APP_VERSION = (Get-Content -Path pubspec.yaml | Select-String -Pattern 'version:' | ForEach-Object { $_.Line.Split(':')[1].Trim() })
          echo "APP_VERSION=$APP_VERSION" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "APP_NAME=$APP_NAME" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh

      - name: Print APP_NAME and APP_VERSION  for Windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "The app name is ${{ env.APP_NAME }}"
          echo "The app version is ${{ env.APP_VERSION }}"
        shell: pwsh

      - name: Upload Windows build to GitHub Release
        if: matrix.os == 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ needs.build.outputs.upload_url }}
          asset_path: ./release/release-${{ env.APP_NAME }}-${{ env.APP_VERSION }}.exe
          asset_name: release-${{ env.APP_NAME }}-${{ env.APP_VERSION }}.exe
          asset_content_type: application/octet-stream

      - name: Upload macOS build to GitHub Release
        if: matrix.os == 'macos-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ needs.build.outputs.upload_url }}
          asset_path: ./release/release-${{ env.APP_NAME }}-${{ env.APP_VERSION }}.dmg
          asset_name: release-${{ env.APP_NAME }}-${{ env.APP_VERSION }}.dmg
          asset_content_type: application/x-apple-diskimage
